# Generated by Django 4.1.3 on 2022-12-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_completed_alter_gameuser_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='hours_played',
            field=models.IntegerField(null=True),
        ),
    ]
