# Generated by Django 4.1.3 on 2022-12-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_gameuser_hours_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='storyline',
            field=models.TextField(default='None', max_length=1000),
        ),
    ]
