# Generated by Django 4.1.3 on 2022-12-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_storyline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='company',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
