# Generated by Django 4.1.3 on 2022-12-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_company_alter_game_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='storyline',
            field=models.TextField(default='None', max_length=2000),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(max_length=2000),
        ),
    ]
