# Generated by Django 4.1.3 on 2022-12-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_game_storyline_alter_game_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='timer_started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='timer_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
