# Generated by Django 4.1.3 on 2022-12-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_game_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cover',
        ),
    ]
