# Generated by Django 4.1.3 on 2022-12-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_game_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='storyline',
            field=models.TextField(default='None', max_length=200000),
        ),
    ]
